### PR TITLE
[FIX] Automate Script

### PR DESCRIPTION
**Pull request by Akash6222**
- [x] Added sudo in for npm packages installation
- [x] Changed 'tar -xvf ~/nvim-linux64.tar.gz' to 'cd ~/ && tar -xvf nvim-linux64.tar.gz'

### CODE REVIEW

**Review by Rishabh672003 — APPROVED** [review]
Dont use this script its very outdated

**Comment by Akash6222** [comment]
On my machine, it's working 🙂
Did you encounter any issues again ?

**Comment by Rishabh672003** [comment]
> On my machine, it's working 🙂
> Did you encounter any issues again ?

I said it's outdated

**Comment by Akash6222** [comment]
Then why it's there 😒

**Comment by Rishabh672003** [comment]
idk i will update it later

**Pull request merged**
